title: StreamFlix
description: A simple Netflix-style site
theme: jekyll-theme-cayman
author: Daniel Adebayo
github:
  is_project_page: true
  repository_url: https://github.com/ddust-tech/StreamFlix
